# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.2.0
_src_path: gh:oca/oca-addons-repo-template
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: This repository includes all the Odoo modules developed to fit the
  specific needs of the Netherlands.
repo_name: l10n-netherlands
repo_slug: l10n-netherlands
travis_apt_packages: []
travis_apt_sources: []
